### PR TITLE
support detect and use corresponding manager and fix windows related error

### LINKED ISSUE #6: Support PNPM and Yarn
Right now `next-on-pages` assumes users are using NPM: https://github.com/cloudflare/next-on-pages/blob/main/src/index.ts#L41

Would be nice if this supported PNPM/Yarn as primary package managers too

### LINKED ISSUE #52: Error: spawn npm ENOENT
When trying to run `npx @cloudflare/next-on-pages` I get an error

```
C:\Users\...\...\project>npx @cloudflare/next-on-pages  
@cloudflare/next-to-pages CLI
⚡️
⚡️ Installing 'vercel' CLI...
⚡️
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install', '-D', 'vercel' ]
}
```

I use
node@16.13.0 and @18.12.0
npm@8.1.0

### PR DESCRIPTION
**Pull request by LOLBRUHNICE**
This PR is created to achieve the following things: 
1. Use the package manager that was used in the project to build
> + yarn v2+ without `nodeLinker` set to `node-modules` isn't supported since vercel build pipeline doesn't support Plug'n'Play
2. fix `spawn npm ENOENT` error occured when running on windows
3. normalize path when running on windows (back slash to forward slash) so esbuild can identify the path properly
> slash normalization changes:
> + [L544-L547](https://github.com/LOLBRUHNICE/next-on-pages/blob/main/src/index.ts#L544-L547)
> + [L557](https://github.com/LOLBRUHNICE/next-on-pages/blob/main/src/index.ts#L557)
> + [L571-574](https://github.com/LOLBRUHNICE/next-on-pages/blob/main/src/index.ts#L571-L574)
> + [L575-578](https://github.com/LOLBRUHNICE/next-on-pages/blob/main/src/index.ts#L575-L578)

Fixes #52

### CODE REVIEW

**Comment by LOLBRUHNICE** [comment]
Seems like support for Route Group cant be achieved by simply add experimentalResponseStreaming detection, so i removed it

**Comment by LucasLundJensen** [comment]
This PR solved my exact issue.
+1 for merging this into main branch.

For reference, I got the following error:

```
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install', '-D', 'vercel' ]
}
```

**Comment by danburonline** [comment]
Is this ready to merge?

**Review by Cherry — CHANGES_REQUESTED** [review]
I would recommend you revert the formatting changes. Cloudflare uses tabs in most of its JS/TS projects these days since they're better for accessibility. See https://github.com/cloudflare/wrangler2/issues/1298 for details.

Adding an `.editorconfig` and prettier config is a good idea - but I'd grab it from https://github.com/cloudflare/wrangler2 and in another PR.

**Comment by LOLBRUHNICE** [comment]
> I would recommend you revert the formatting changes. Cloudflare uses tabs in most of its JS/TS projects these days since they're better for accessibility. See [cloudflare/wrangler2#1298](https://github.com/cloudflare/wrangler2/issues/1298) for details.
> 
> Adding an `.editorconfig` and prettier config is a good idea - but I'd grab it from https://github.com/cloudflare/wrangler2 and in another PR.

I have changed the formatting config, same as the config of wrangler2

**Comment by hanford** [comment]
@LOLBRUHNICE how is this different than the PR I [opened](https://github.com/cloudflare/next-on-pages/pull/11)?

**Comment by LOLBRUHNICE** [comment]
> @LOLBRUHNICE how is this different than the PR I [opened](https://github.com/cloudflare/next-on-pages/pull/11)?

I noticed that your pr only utilize the package manager when installing vercel, for the building it still use npx, so I created this pr to fully utilize the consumer package manager. Instead of installing vercel, I made it directly use dlx for yarn and pnpm, and use npx for npm(though yarn classic still need to install the vercel first)

Besides I created this pr to solve some Windows related problem also

**Comment by LOLBRUHNICE** [comment]
so there are differences between your pr and this pr

**Comment by szymondlugolecki** [comment]
Would love this to be merged, so I could finally use next-on-pages after a month of waiting #52

**Comment by Pavel-Sushko** [comment]
Please merge 🙏🏻

**Comment by dario-piotrowicz** [comment]
Hello @LOLBRUHNICE Thank you so very much for this PR, and sorry it hasn't been reviewed in a while 🙇 

I am sorry for being a bother but this PR is quite large and broad in scope so it's quite difficult to tackle, moreover it contains some code that goes against changes we applied recently, like the use of package managers: https://github.com/cloudflare/next-on-pages/pull/71 (or the Windows fix that is being addressed by https://github.com/cloudflare/next-on-pages/pull/86)

(I also did open a PR with prettier since by its title and description I didn't think this PR was setting it up: https://github.com/cloudflare/next-on-pages/pull/90)

If it were not too much trouble it would be fantastic if you could remove everything from this PR that isn't specific for point `3` in your description (or close this PR and open a new one if you prefer) 🙏, so that we can land that quickly (if it is too much trouble let me know, and I can apply the change for you here)

___

Again I am very sorry for this, we've had issues with finding the time to address PRs and some like this haven't gotten the attention they deserved, we're putting a significant effort to improve this and try to reviews PRs from now on much more swiftly.

Also we hope you will continue contributing to the project, if you do, please try to keep PRs smaller and more focused so that they are easier and quicker to review and merge (and other PRs implementing the same changes don't go against it)

**Comment by LOLBRUHNICE** [comment]
> Hello @LOLBRUHNICE Thank you so very much for this PR, and sorry it hasn't been reviewed in a while 🙇 
> 
> I am sorry for being a bother but this PR is quite large and broad in scope so it's quite difficult to tackle, moreover it contains some code that goes against changes we applied recently, like the use of package managers: https://github.com/cloudflare/next-on-pages/pull/71 (or the Windows fix that is being addressed by https://github.com/cloudflare/next-on-pages/pull/86)
> 
> (I also did open a PR with prettier since by its title and description I didn't think this PR was setting it up: https://github.com/cloudflare/next-on-pages/pull/90)
> 
> If it were not too much trouble it would be fantastic if you could remove everything from this PR that isn't specific for point `3` in your description (or close this PR and open a new one if you prefer) 🙏, so that we can land that quickly (if it is too much trouble let me know, and I can apply the change for you here)
> 
> ___
> 
> Again I am very sorry for this, we've had issues with finding the time to address PRs and some like this haven't gotten the attention they deserved, we're putting a significant effort to improve this and try to reviews PRs from now on much more swiftly.
> 
> Also we hope you will continue contributing to the project, if you do, please try to keep PRs smaller and more focused so that they are easier and quicker to review and merge (and other PRs implementing the same changes don't go against it)
> 
> 

ok, I will create a new pr and try to keep the changes as simple as I can

**Comment by dario-piotrowicz** [comment]
@LOLBRUHNICE thank you so very much! sorry about it again 🙇

**Pull request closed without merging**
