### PR TITLE
Fix #8

### LINKED ISSUE #8: npx @cloudflare/next-on-pages error during build
I received the following errors during `npx @cloudflare/next-on-pages` build step, after `Completed 'npx vercel build'`. These are repeated for all page files:

```
    {
      detail: undefined,
      id: '',
      location: {
        column: 8,
        file: '../../../tmp/ge1zkztc959/about.func.js',
        length: 2,
        line: 13617,
        lineText: '    true=>{(!C||s)&&(i&&clearTimeout(i),i=setTimeout(()=>{n.done(!0)},t))},"routeChangeError");return w(`',
        namespace: '',
        suggestion: ';'
      },
      notes: [],
      pluginName: '',
      text: 'Expected ";" but found "=>"'
    },
```

Though these errors seem to be ignored with Node 14, Node 16 would fail the build entirely. Happy to include the entire log, though it's mostly just a repeat of the above for all the pages.

And, I'm not sure if this is related, but all of the `getServerSideProps` pages return 404, while the static pages work as expected.

This project runs `next@12.3.1`, `react@18.2.0`.

Thank you!

### PR DESCRIPTION
**Pull request by aidenwallis**
Implements the fix mentioned in #8 - I found that this regex also fixed my Next.js 13 project on Pages.

### CODE REVIEW

**Review by debanjanbasu — APPROVED** [review]
Can we get this merged asap 🙏? This might fix nectjs13 issues "Identifier 'n' has already been declared".

**Comment by hckhanh** [comment]
Hi @GregBrimble, Can we get it done?

**Review by debanjanbasu — APPROVED** [review]

**Comment by debanjanbasu** [comment]
On applying this patch, I'm getting:

⚡️ ERROR: Could not map all functions to an entry in the manifest.
⚡️ Please report this at https://github.com/cloudflare/next-on-pages/issues.

`if (hydratedMiddleware.size + hydratedFunctions.size !== functionsMap.size) {
    console.error(
      "\u26A1\uFE0F ERROR: Could not map all functions to an entry in the manifest."
    );
    console.error(
      "\u26A1\uFE0F Please report this at https://github.com/cloudflare/next-on-pages/issues."
    );
    (0, import_process.exit)(1);
  }`
  
  
It seems to be coming from the above lines.

**Comment by hckhanh** [comment]
I get this too, perhaps this is related to the file structure of Next 13. I think we need to inspect that

**Comment by aidenwallis** [comment]
Hey all,

This change isn't aiming to add any support to Next.js 13. It may be worth tracking the original issue for that: #6

This only aims to fix an issue noticed originally in #8

It looks like others are running into this issue over there too!

**Comment by debanjanbasu** [comment]
To all those, please try with nextjs 13, but not with TypeScript. The regular vanilla JS version works fine with this patch.

**Comment by GregBrimble** [comment]
Thank you very much for the PR!

**Pull request merged**
