### PR TITLE
Fix the issue of refetching the vercel package every single time when using yarn berry.

### LINKED ISSUE #240: [🐛 Bug]: Re-fetch the Vercel package from the network every time when update in `--watch` mode
### next-on-pages environment related information

System:
        Platform: darwin
        Arch: arm64
        Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
        CPU: (10) arm64 Apple M1 Max
        Memory: 32 GB
        Shell: /bin/zsh
Binaries:
        Node: 19.6.1
        Yarn: 3.3.0
        npm: 9.4.0
        pnpm: N/A
Package Manager Used: yarn (berry)
Relevant Packages:
        @cloudflare/next-on-pages: 0.10.1
        vercel: N/A
        next: N/A

### Description

I have installed `@cloudflare/next-on-pages`, `vercel` and `wrangler` to the dependencies of my project. I added `"cf:watch": "yarn next-on-pages --watch"` to the `scripts` of `package.json`.

Then when I run `yarn cf:watch` in terminal, every time I update my code, `@cloudflare/next-on-pages` will refetch the `vercel` package from network, so the action is soooo slow.

After checked the source code in this repo, I found you are using `yarn dlx` to execute the vercel building in `yarn (berry)` environment. The code in `next-on-pages/src/buildApplication/buildVercelOutput.ts#84` is following:

```ts
const vercelBuild = spawn(pkgMngCMD, [
	...(pkgMng === 'yarn (berry)' ? ['dlx'] : []),
	'vercel',
	'build',
]);
``` 

Since the `yarn dlx` will refetch the package from npm registry every time, so it do in `--watch` mode. And I tested with to delete the line `...(pkgMng === 'yarn (berry)' ? ['dlx'] : []),` in above code, and it's to do things correctly without refetching.

Maybe you guys could consider run vercel building with `yarn vercel` directly when the `vercel` package is added to the project dependencies?

### Reproduction

_No response_

### Pages Deployment Method

None

### Pages Deployment ID

_No response_

### Additional Information

_No response_

### Would you like to help?

- [X] Would you like to help fixing this bug?

### PR DESCRIPTION
**Pull request by noobnooc**
As described in #240 , when using yarn berry, `next-on-pages` will refetch the vercel package every single time even it's in `--watch` mode. So, I fixed that by checking whether the vercel package has been installed locally. If it's installed, then run Vercel building with `yarn vercel build` instead of `yarn dlx vercel build`.

Fixes #240 .

### CODE REVIEW

**Comment by dario-piotrowicz** [comment]
Thanks a lot @noobnooc 🙂 

Seems like your change has some type issues, also your if statement seems a bit hard to read (I imagine that that's why you added those comments in)

I think that something like the following you be pretty nice:
```diff
--- a/src/buildApplication/buildVercelOutput.ts
+++ b/src/buildApplication/buildVercelOutput.ts
@@ -1,5 +1,5 @@
 import { writeFile, mkdir, rm, rmdir } from 'fs/promises';
-import { spawn } from 'child_process';
+import { spawn, type ChildProcessWithoutNullStreams } from 'child_process';
 import { join, resolve } from 'path';
 import { cliLog } from '../cli';
 import { validateDir, validateFile } from '../utils';
@@ -81,25 +81,7 @@ async function runVercelBuild(pkgMng: PackageManager): Promise<void> {
 
        cliLog('Building project...');
 
-       let vercelBuild: ReturnType<typeof spawn>;
-
-       // If the package manager is yarn (berry), and the `vercel` package has not been installed,
-       // Then execute vercel building with `yarn dlx`.
-       if (
-               pkgMng === 'yarn (berry)' &&
-               // Check if the vercel package has been installed
-               !(await new Promise(resolve => {
-                       const vercelChecking = spawn(pkgMngCMD, ['info', 'vercel']);
-
-                       vercelChecking.on('exit', code => {
-                               resolve(code === 0);
-                       });
-               }))
-       ) {
-               vercelBuild = spawn(pkgMngCMD, ['dlx', 'vercel', 'build']);
-       } else {
-               vercelBuild = spawn(pkgMngCMD, ['vercel', 'build']);
-       }
+       const vercelBuild = await getVercelBuildChildProcess(pkgMng, pkgMngCMD);
 
        vercelBuild.stdout.on('data', data =>
                cliLog(`\n${data}`, { fromVercelCli: true })
@@ -122,6 +104,27 @@ async function runVercelBuild(pkgMng: PackageManager): Promise<void> {
        });
 }
 
+async function getVercelBuildChildProcess(
+       pkgMng: PackageManager,
+       pkgMngCMD: string
+): Promise<ChildProcessWithoutNullStreams> {
+       if (pkgMng === 'yarn (berry)') {
+               const vercelPackageIsInstalled = !(await new Promise(resolve => {
+                       const vercelChecking = spawn(pkgMngCMD, ['info', 'vercel']);
+
+                       vercelChecking.on('exit', code => {
+                               resolve(code === 0);
+                       });
+               }));
+
+               if (vercelPackageIsInstalled) {
+                       return spawn(pkgMngCMD, ['dlx', 'vercel', 'build']);
+               }
+       }
+
+       return spawn(pkgMngCMD, ['vercel', 'build']);
+}
+
 /**
  * Vercel and Next.js generate *private* files for telemetry purposes that are accessible as static assets (`.vercel/output/static/_next/__private/...`).
  *
```

it fixes both issues and makes the if statement more readable, making extra comments unncessary

Please let me know what you think 🙂 
(and/or if you have other ideas)

**Comment by noobnooc** [comment]
Due to some reason, my vscode did not show the type error, so I didn't realize it, sorry for that.

The change you proposed dose make the code much clearer. Since I rarely participate in open source projects and am not familiar with the process, I try to make as few changes to the code as possible, which led to me mixing everything together.

I have pushed a new commit to do that change, or you can also make changes in your own way.. If there is any other issue, you can let me know, so that I can become familiar with the process of participating in open-source projects and make some contributions to the community in the future :)

**Review by dario-piotrowicz — APPROVED** [review]

**Comment by dario-piotrowicz** [comment]
@noobnooc I have just tried pnpm and the solution with it would be quite different from the yarn one you added (since I think `pnpm info` fetches from the registry and gives you the information of non-installed packages, it seems like it's also undocumented: https://github.com/pnpm/pnpm/issues/5935 😓)

So I think for now we should just go with your solution and handle pnpm separately 🙂

**Comment by dario-piotrowicz** [comment]
Thanks a lot again for the contribution 😄

**Comment by dario-piotrowicz** [comment]
@noobnooc I've opened an issue for `pnpm`: https://github.com/cloudflare/next-on-pages/issues/262
(I'll look into that soon 🙂)

**Pull request merged**
